# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Elecelf
tagline:          '  Technology is to enjoy.'
description:      '<br /><br /><br />'
url:              http://snakealpha.github.io/
paginate:         8

author:
  name:           'Snake Liu'
  url:            http://weibo.com/u/3029729233

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
